// Curated lucide icon catalogue for Quick actions. A fixed map (not a dynamic
// `lucide-react/dynamic` import) keeps the client bundle small while still
// giving the picker plenty of choice. The map also understands the sidebar /
// nav / form icon-key vocabulary so imported destinations keep their icon;
// resolve at the render site with `QUICK_ACTION_ICONS[key] ?? FALLBACK_ICON`.

import {
  Activity,
  AlertTriangle,
  BarChart3,
  Bell,
  BookOpen,
  Calendar,
  Camera,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cog,
  Download,
  Droplets,
  FileCheck,
  FileText,
  Flag,
  Flame,
  Folder,
  Gauge,
  GraduationCap,
  Hammer,
  HardHat,
  HeartPulse,
  Image as ImageIcon,
  Key,
  Link2,
  ListChecks,
  Lock,
  Mail,
  Map as MapIcon,
  MapPin,
  NotebookPen,
  Package,
  PenLine,
  Phone,
  PlayCircle,
  Plus,
  Radiation,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Star,
  Thermometer,
  TrafficCone,
  Truck,
  Upload,
  User,
  Users,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Primary keys shown in the icon picker grid, in display order. */
export const ICON_PICKER_KEYS = [
  'zap',
  'plus',
  'alert',
  'shield-alert',
  'shield',
  'siren',
  'radiation',
  'flame',
  'droplet',
  'hard-hat',
  'traffic-cone',
  'hammer',
  'wrench',
  'cog',
  'clipboard',
  'clipboard-check',
  'list-checks',
  'check',
  'file',
  'file-check',
  'folder',
  'book',
  'grad',
  'journal',
  'pencil',
  'users',
  'user',
  'pin',
  'map',
  'truck',
  'box',
  'gauge',
  'activity',
  'chart',
  'bell',
  'calendar',
  'clock',
  'camera',
  'image',
  'phone',
  'mail',
  'link',
  'search',
  'settings',
  'star',
  'flag',
  'heart',
  'thermometer',
  'key',
  'lock',
  'play',
  'download',
  'upload',
] as const

// Full resolver map: every picker key + a handful of aliases for the icon-key
// vocabularies used elsewhere (sidebar nav, form templates) so an imported
// destination renders with a sensible glyph instead of the fallback.
export const QUICK_ACTION_ICONS: Record<string, LucideIcon> = {
  zap: Zap,
  plus: Plus,
  alert: AlertTriangle,
  'shield-alert': ShieldAlert,
  shield: ShieldCheck,
  siren: Siren,
  radiation: Radiation,
  flame: Flame,
  droplet: Droplets,
  'hard-hat': HardHat,
  'traffic-cone': TrafficCone,
  hammer: Hammer,
  wrench: Wrench,
  cog: Cog,
  clipboard: ClipboardList,
  'clipboard-check': ClipboardCheck,
  'list-checks': ListChecks,
  check: CheckCircle2,
  file: FileText,
  'file-check': FileCheck,
  folder: Folder,
  book: BookOpen,
  grad: GraduationCap,
  journal: NotebookPen,
  pencil: PenLine,
  users: Users,
  user: User,
  pin: MapPin,
  map: MapIcon,
  truck: Truck,
  box: Package,
  gauge: Gauge,
  activity: Activity,
  chart: BarChart3,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  camera: Camera,
  image: ImageIcon,
  phone: Phone,
  mail: Mail,
  link: Link2,
  search: Search,
  settings: Settings,
  star: Star,
  flag: Flag,
  heart: HeartPulse,
  thermometer: Thermometer,
  key: Key,
  lock: Lock,
  play: PlayCircle,
  download: Download,
  upload: Upload,
  // Aliases for sidebar / form-template icon keys -------------------------
  'circle-user': User,
  message: Mail,
  timer: Clock,
  library: BookOpen,
  construction: TrafficCone,
  award: Star,
  rss: Activity,
  'list-check': ListChecks,
  graduation: GraduationCap,
}

/**
 * Neutral fallback glyph. Resolve an icon at the render site with a member
 * expression — `QUICK_ACTION_ICONS[key] ?? FALLBACK_ICON` — rather than a helper
 * call, so the react-hooks/static-components lint rule stays happy (it flags
 * capitalised components produced by a function call during render).
 */
export const FALLBACK_ICON: LucideIcon = Zap
