// FlowSubjectProfile per native module — the pure-data description that drives
// the SAME FlowsCanvas (which triggers/actions/status/fields it offers) and the
// lint. Field keys here MUST match the keys each module's adapter loadValues()
// returns, so conditions / {{interpolation}} / recipient `field` targets resolve.

import type { FlowSubjectProfile } from '@beaconhs/forms-core'

export const MODULE_FLOW_PROFILES: Record<string, FlowSubjectProfile> = {
  journals: {
    subjectType: 'module',
    subjectKey: 'journals',
    label: 'Journals',
    triggers: ['on_submit', 'on_delete', 'manual'],
    actions: [
      'send_email',
      'notify_role',
      'create_capa',
      'webhook',
      'change_status',
      'duplicate_record',
      'export_pdf',
    ],
    statusValues: ['draft', 'submitted', 'archived'],
    fields: [
      { key: 'status', label: 'Status', kind: 'enum' },
      { key: 'reference', label: 'Reference', kind: 'text' },
      { key: 'title', label: 'Title', kind: 'text' },
      { key: 'body_text', label: 'Body text', kind: 'text' },
      { key: 'entry_date', label: 'Entry date', kind: 'date' },
      { key: 'author_name', label: 'Author name', kind: 'text' },
      { key: 'supervisor_name', label: 'Supervisor name', kind: 'text' },
      { key: 'site_name', label: 'Site name', kind: 'text' },
      { key: 'tags', label: 'Tags', kind: 'text' },
      // FK ids for conditions / recipient `field` targets.
      { key: 'person_id', label: 'Author (person id)', kind: 'person' },
      { key: 'supervisor_person_id', label: 'Supervisor (person id)', kind: 'person' },
      { key: 'site_org_unit_id', label: 'Site (id)', kind: 'org_unit' },
    ],
    collections: [
      {
        key: 'photos',
        label: 'Photos',
        fields: [
          { key: 'url', label: 'Image URL', kind: 'text' },
          { key: 'caption', label: 'Caption', kind: 'text' },
        ],
      },
    ],
  },
  hazid: {
    subjectType: 'module',
    subjectKey: 'hazid',
    label: 'Hazard Assessments',
    richPdf: true,
    triggers: ['on_create', 'on_sign', 'on_lock', 'on_unlock', 'on_delete', 'manual'],
    actions: [
      'send_email',
      'notify_role',
      'create_capa',
      'webhook',
      'change_status',
      'duplicate_record',
      'export_pdf',
    ],
    fields: [
      { key: 'reference', label: 'Reference', kind: 'text' },
      { key: 'job_scope', label: 'Job scope', kind: 'text' },
      { key: 'location_on_site', label: 'Location on site', kind: 'text' },
      { key: 'locked', label: 'Locked', kind: 'bool' },
      { key: 'in_progress', label: 'In progress', kind: 'bool' },
      { key: 'status_label', label: 'Status', kind: 'text' },
      { key: 'occurred_at', label: 'Occurred at', kind: 'date' },
      { key: 'site_name', label: 'Site name', kind: 'text' },
      { key: 'project_name', label: 'Project name', kind: 'text' },
      { key: 'type_name', label: 'Assessment type name', kind: 'text' },
      { key: 'supervisor_name', label: 'Supervisor name', kind: 'text' },
      { key: 'reported_by_name', label: 'Reported by', kind: 'text' },
      { key: 'locked_at', label: 'Locked at', kind: 'date' },
      // Section-visibility flags from the assessment type ({{#if …}} gates).
      { key: 'show_job_scope', label: 'Show job scope section', kind: 'bool' },
      { key: 'show_ppe', label: 'Show PPE section', kind: 'bool' },
      { key: 'show_questions', label: 'Show questions section', kind: 'bool' },
      { key: 'show_tasks', label: 'Show tasks section', kind: 'bool' },
      { key: 'show_hazards', label: 'Show hazards section', kind: 'bool' },
      // FK ids kept for conditions / recipient `field` targets.
      { key: 'site_org_unit_id', label: 'Site (id)', kind: 'org_unit' },
      { key: 'project_org_unit_id', label: 'Project (id)', kind: 'org_unit' },
      { key: 'supervisor_person_id', label: 'Supervisor (person id)', kind: 'person' },
      { key: 'assessment_type_id', label: 'Assessment type (id)', kind: 'text' },
    ],
    collections: [
      {
        key: 'tasks',
        label: 'Tasks',
        fields: [
          { key: 'name', label: 'Task', kind: 'text' },
          { key: 'controls', label: 'Controls', kind: 'text' },
        ],
      },
      {
        key: 'hazards',
        label: 'Hazards & controls',
        fields: [
          { key: 'name', label: 'Hazard', kind: 'text' },
          { key: 'standard_controls', label: 'Standard controls', kind: 'text' },
          { key: 'specific_controls', label: 'Specific controls', kind: 'text' },
          { key: 'controls', label: 'Controls', kind: 'text' },
          { key: 'applicable', label: 'Applicable', kind: 'text' },
          { key: 'pre_likelihood', label: 'Pre likelihood', kind: 'number' },
          { key: 'pre_severity', label: 'Pre severity', kind: 'number' },
          { key: 'pre_risk', label: 'Pre risk (L×S)', kind: 'number' },
          { key: 'post_likelihood', label: 'Post likelihood', kind: 'number' },
          { key: 'post_severity', label: 'Post severity', kind: 'number' },
          { key: 'post_risk', label: 'Post risk (L×S)', kind: 'number' },
        ],
      },
      {
        key: 'ppe',
        label: 'PPE',
        fields: [
          { key: 'name', label: 'PPE', kind: 'text' },
          { key: 'description', label: 'Description', kind: 'text' },
          { key: 'required', label: 'Required', kind: 'text' },
          { key: 'answer', label: 'Answer', kind: 'text' },
        ],
      },
      {
        key: 'questions',
        label: 'Questions',
        fields: [
          { key: 'question', label: 'Question', kind: 'text' },
          { key: 'answer', label: 'Answer', kind: 'text' },
          { key: 'requires_yes', label: 'Requires yes', kind: 'text' },
        ],
      },
      {
        key: 'signatures',
        label: 'Signatures',
        fields: [
          { key: 'name', label: 'Name', kind: 'text' },
          { key: 'type', label: 'Type', kind: 'text' },
          { key: 'cs_entrant', label: 'CS entrant', kind: 'text' },
          { key: 'cs_attendant', label: 'CS attendant', kind: 'text' },
          { key: 'cs_rescue', label: 'CS rescue', kind: 'text' },
          { key: 'signed_at', label: 'Signed at', kind: 'text' },
          { key: 'image', label: 'Signature image (data URL)', kind: 'text' },
        ],
      },
      {
        key: 'photos',
        label: 'Photos',
        fields: [
          { key: 'url', label: 'Image URL', kind: 'text' },
          { key: 'caption', label: 'Caption', kind: 'text' },
        ],
      },
    ],
  },
  incidents: {
    subjectType: 'module',
    subjectKey: 'incidents',
    label: 'Incidents',
    richPdf: true,
    triggers: ['on_create', 'status_change', 'on_lock', 'on_unlock', 'manual'],
    actions: [
      'send_email',
      'notify_role',
      'create_capa',
      'webhook',
      'change_status',
      'duplicate_record',
      'export_pdf',
    ],
    statusValues: ['reported', 'under_investigation', 'pending_review', 'closed', 'reopened'],
    fields: [
      { key: 'reference', label: 'Reference', kind: 'text' },
      { key: 'title', label: 'Title', kind: 'text' },
      { key: 'status_label', label: 'Status', kind: 'text' },
      { key: 'type_label', label: 'Type', kind: 'text' },
      { key: 'severity_label', label: 'Severity', kind: 'text' },
      { key: 'occurred_at', label: 'Occurred at', kind: 'date' },
      { key: 'reported_at', label: 'Reported at', kind: 'date' },
      { key: 'closed_at', label: 'Closed at', kind: 'date' },
      { key: 'location', label: 'Location on site', kind: 'text' },
      { key: 'weather', label: 'Weather', kind: 'text' },
      { key: 'description', label: 'Description', kind: 'text' },
      { key: 'events_leading_up', label: 'Events leading up', kind: 'text' },
      { key: 'immediate_action_taken', label: 'Immediate action taken', kind: 'text' },
      { key: 'ppe_worn', label: 'PPE worn', kind: 'text' },
      { key: 'root_cause', label: 'Root cause', kind: 'text' },
      { key: 'foreman_text', label: 'Foreman', kind: 'text' },
      { key: 'external_people_involved', label: 'External people involved', kind: 'text' },
      { key: 'witnesses', label: 'Witnesses', kind: 'text' },
      { key: 'classification_labels', label: 'Classification', kind: 'text' },
      // Medical / regulatory flags (booleans — use {{#if …}} to gate sections).
      { key: 'critical_injury', label: 'Critical injury', kind: 'bool' },
      { key: 'ministry_of_labour_notified', label: 'Ministry of Labour notified', kind: 'bool' },
      { key: 'ems_notified', label: 'EMS notified', kind: 'bool' },
      { key: 'first_aid_received', label: 'First aid received', kind: 'bool' },
      { key: 'first_aid_provider', label: 'First aid provider', kind: 'text' },
      { key: 'medical_attention_received', label: 'Medical attention received', kind: 'bool' },
      { key: 'treated_at_hospital', label: 'Treated at (hospital)', kind: 'text' },
      { key: 'treated_in_city', label: 'Treated in (city)', kind: 'text' },
      { key: 'transportation', label: 'Transportation', kind: 'text' },
      { key: 'lost_time', label: 'Lost time', kind: 'bool' },
      { key: 'lost_time_first_day', label: 'Lost time first day', kind: 'date' },
      { key: 'lost_time_last_day', label: 'Lost time last day', kind: 'date' },
      { key: 'lost_time_days', label: 'Lost time days', kind: 'number' },
      { key: 'modified_duty', label: 'Modified duty', kind: 'bool' },
      { key: 'modified_duty_first_day', label: 'Modified duty first day', kind: 'date' },
      { key: 'modified_duty_last_day', label: 'Modified duty last day', kind: 'date' },
      { key: 'modified_duty_days', label: 'Modified duty days', kind: 'number' },
      { key: 'externally_reportable', label: 'Externally reportable', kind: 'bool' },
      { key: 'actual_severity', label: 'Actual severity (1–5)', kind: 'number' },
      { key: 'potential_severity', label: 'Potential severity (1–5)', kind: 'number' },
      { key: 'site_name', label: 'Site name', kind: 'text' },
      { key: 'department_name', label: 'Department name', kind: 'text' },
      { key: 'supervisor_name', label: 'Supervisor name', kind: 'text' },
      { key: 'reported_by_name', label: 'Reported by', kind: 'text' },
      // raw enums + FK ids for conditions / recipient targets.
      { key: 'status', label: 'Status (raw)', kind: 'enum' },
      { key: 'type', label: 'Type (raw)', kind: 'enum' },
      { key: 'severity', label: 'Severity (raw)', kind: 'enum' },
      { key: 'site_org_unit_id', label: 'Site (id)', kind: 'org_unit' },
      { key: 'department_id', label: 'Department (id)', kind: 'text' },
      { key: 'supervisor_person_id', label: 'Supervisor (person id)', kind: 'person' },
    ],
    collections: [
      {
        key: 'people_involved',
        label: 'People involved',
        fields: [
          { key: 'name', label: 'Name', kind: 'text' },
          { key: 'role', label: 'Role', kind: 'text' },
        ],
      },
      {
        key: 'injuries',
        label: 'Injuries',
        fields: [
          { key: 'person_name', label: 'Person', kind: 'text' },
          { key: 'body_parts', label: 'Body parts', kind: 'text' },
          { key: 'injury_types', label: 'Injury types', kind: 'text' },
          { key: 'treatment', label: 'Treatment', kind: 'text' },
          { key: 'treated_at_facility', label: 'Treated at', kind: 'text' },
          { key: 'worked_hours_prior_to', label: 'Hours worked prior', kind: 'number' },
        ],
      },
      {
        key: 'lost_time_events',
        label: 'Lost-time events',
        fields: [
          { key: 'status', label: 'Status', kind: 'text' },
          { key: 'valid_from', label: 'From', kind: 'text' },
          { key: 'valid_to', label: 'To', kind: 'text' },
          { key: 'notes', label: 'Notes', kind: 'text' },
        ],
      },
      {
        key: 'events',
        label: 'Events',
        fields: [
          { key: 'occurred_at', label: 'When', kind: 'text' },
          { key: 'description', label: 'Description', kind: 'text' },
          { key: 'recorded_by_name', label: 'Recorded by', kind: 'text' },
        ],
      },
      {
        key: 'contributing_factors',
        label: 'Contributing factors',
        fields: [
          { key: 'category', label: 'Category', kind: 'text' },
          { key: 'description', label: 'Description', kind: 'text' },
        ],
      },
      {
        key: 'preventative_steps',
        label: 'Preventative steps',
        fields: [
          { key: 'description', label: 'Description', kind: 'text' },
          { key: 'owner_name', label: 'Owner', kind: 'text' },
          { key: 'target_date', label: 'Target date', kind: 'text' },
          { key: 'status', label: 'Status', kind: 'text' },
        ],
      },
      {
        key: 'photos',
        label: 'Photos',
        fields: [
          { key: 'url', label: 'Image URL', kind: 'text' },
          { key: 'caption', label: 'Caption', kind: 'text' },
        ],
      },
    ],
  },
  'corrective-actions': {
    subjectType: 'module',
    subjectKey: 'corrective-actions',
    label: 'Corrective Actions',
    richPdf: true,
    triggers: ['on_create', 'status_change', 'manual'],
    actions: [
      'send_email',
      'notify_role',
      'webhook',
      'change_status',
      'duplicate_record',
      'export_pdf',
    ],
    statusValues: ['open', 'in_progress', 'pending_verification', 'closed', 'cancelled'],
    fields: [
      { key: 'reference', label: 'Reference', kind: 'text' },
      { key: 'title', label: 'Title', kind: 'text' },
      { key: 'status_label', label: 'Status', kind: 'text' },
      { key: 'severity_label', label: 'Severity', kind: 'text' },
      { key: 'source_label', label: 'Source', kind: 'text' },
      { key: 'source_entity_type', label: 'Source record type', kind: 'text' },
      { key: 'description', label: 'Description', kind: 'text' },
      { key: 'root_cause', label: 'Root cause', kind: 'text' },
      { key: 'action_taken', label: 'Action taken', kind: 'text' },
      { key: 'assigned_on', label: 'Assigned on', kind: 'date' },
      { key: 'due_on', label: 'Due on', kind: 'date' },
      { key: 'closed_at', label: 'Closed at', kind: 'date' },
      { key: 'cost_impact', label: 'Cost impact', kind: 'text' },
      { key: 'verification_required', label: 'Verification required', kind: 'bool' },
      { key: 'verification_notes', label: 'Verification notes', kind: 'text' },
      { key: 'verifier_name', label: 'Verified by', kind: 'text' },
      { key: 'verified_at', label: 'Verified at', kind: 'date' },
      { key: 'site_name', label: 'Site name', kind: 'text' },
      { key: 'owner_name', label: 'Owner name', kind: 'text' },
      { key: 'assigned_by_name', label: 'Assigned by', kind: 'text' },
      { key: 'status', label: 'Status (raw)', kind: 'enum' },
      { key: 'severity', label: 'Severity (raw)', kind: 'enum' },
      { key: 'source', label: 'Source (raw)', kind: 'enum' },
      { key: 'site_org_unit_id', label: 'Site (id)', kind: 'org_unit' },
      { key: 'owner_tenant_user_id', label: 'Owner (user id)', kind: 'person' },
    ],
    collections: [
      {
        key: 'complete_steps',
        label: 'Completion steps',
        fields: [
          { key: 'kind', label: 'Kind', kind: 'text' },
          { key: 'description', label: 'Description', kind: 'text' },
          { key: 'completed_by_name', label: 'Completed by', kind: 'text' },
          { key: 'completed_at', label: 'Completed at', kind: 'text' },
          { key: 'signature_image', label: 'Signature image (data URL)', kind: 'text' },
        ],
      },
      {
        key: 'photos',
        label: 'Photos',
        fields: [
          { key: 'url', label: 'Image URL', kind: 'text' },
          { key: 'caption', label: 'Caption', kind: 'text' },
        ],
      },
    ],
  },
  inspections: {
    subjectType: 'module',
    subjectKey: 'inspections',
    label: 'Inspections',
    triggers: ['on_create', 'on_submit', 'status_change', 'manual'],
    actions: [
      'send_email',
      'notify_role',
      'create_capa',
      'webhook',
      'change_status',
      'duplicate_record',
      'export_pdf',
    ],
    statusValues: ['draft', 'in_progress', 'submitted', 'closed'],
    fields: [
      { key: 'reference', label: 'Reference', kind: 'text' },
      { key: 'status_label', label: 'Status', kind: 'text' },
      { key: 'type_name', label: 'Inspection type', kind: 'text' },
      { key: 'occurred_at', label: 'Occurred at', kind: 'date' },
      { key: 'site_name', label: 'Site name', kind: 'text' },
      { key: 'inspector_name', label: 'Inspector', kind: 'text' },
      { key: 'supervisor_name', label: 'Supervisor', kind: 'text' },
      { key: 'notes', label: 'Notes', kind: 'text' },
      { key: 'status', label: 'Status (raw)', kind: 'enum' },
      { key: 'type_id', label: 'Inspection type (id)', kind: 'text' },
      { key: 'site_org_unit_id', label: 'Site (id)', kind: 'org_unit' },
      { key: 'inspector_tenant_user_id', label: 'Inspector (user id)', kind: 'person' },
    ],
    collections: [
      {
        key: 'criteria',
        label: 'Inspection items',
        fields: [
          { key: 'group', label: 'Group', kind: 'text' },
          { key: 'question', label: 'Item', kind: 'text' },
          { key: 'answer', label: 'Answer', kind: 'text' },
          { key: 'severity', label: 'Severity', kind: 'text' },
          { key: 'non_compliance', label: 'Non-compliance', kind: 'text' },
          { key: 'action_taken', label: 'Action taken', kind: 'text' },
        ],
      },
      {
        key: 'photos',
        label: 'Photos',
        fields: [
          { key: 'url', label: 'Image URL', kind: 'text' },
          { key: 'caption', label: 'Caption', kind: 'text' },
        ],
      },
    ],
  },
  training: {
    subjectType: 'module',
    subjectKey: 'training',
    label: 'Training',
    triggers: ['on_submit', 'manual'],
    actions: ['send_email', 'notify_role', 'webhook', 'export_pdf'],
    statusValues: ['in_progress', 'submitted', 'cancelled'],
    fields: [
      { key: 'assessment_name', label: 'Assessment', kind: 'text' },
      { key: 'assessment_description', label: 'Assessment description', kind: 'text' },
      { key: 'person_name', label: 'Person', kind: 'text' },
      { key: 'status_label', label: 'Status', kind: 'text' },
      { key: 'pass_fail', label: 'Pass / fail', kind: 'text' },
      { key: 'score_percent', label: 'Score', kind: 'text' },
      { key: 'passing_score', label: 'Passing score', kind: 'text' },
      { key: 'completed_at', label: 'Completed at', kind: 'date' },
      { key: 'status', label: 'Status (raw)', kind: 'enum' },
      { key: 'score', label: 'Score (number)', kind: 'number' },
      { key: 'passed', label: 'Passed (bool)', kind: 'bool' },
      { key: 'type_id', label: 'Assessment type (id)', kind: 'text' },
      { key: 'person_id', label: 'Person (id)', kind: 'person' },
    ],
    collections: [
      {
        key: 'questions',
        label: 'Questions & responses',
        fields: [
          { key: 'prompt', label: 'Question', kind: 'text' },
          { key: 'answer', label: 'Answer', kind: 'text' },
          { key: 'correct_answer', label: 'Correct answer', kind: 'text' },
          { key: 'result', label: 'Result', kind: 'text' },
          { key: 'points', label: 'Points', kind: 'text' },
        ],
      },
    ],
  },
  // Training CLASSES (scheduled instructor-led sessions) — distinct from the
  // 'training' subject above, which is one assessment attempt. There is no
  // status column: the lifecycle is derived (scheduled → cancelled | completed)
  // and the class actions fire status_change with the derived value.
  // `attendee_emails` is a comma-separated address list so a send_email
  // recipient `field` target reaches the whole roster.
  'training-classes': {
    subjectType: 'module',
    subjectKey: 'training-classes',
    label: 'Training classes',
    triggers: ['on_create', 'status_change', 'manual'],
    actions: ['send_email', 'notify_role', 'webhook', 'export_pdf'],
    statusValues: ['scheduled', 'cancelled', 'completed'],
    fields: [
      { key: 'title', label: 'Class title', kind: 'text' },
      { key: 'course_name', label: 'Course', kind: 'text' },
      { key: 'course_code', label: 'Course code', kind: 'text' },
      { key: 'course_description', label: 'Course description', kind: 'text' },
      { key: 'status_label', label: 'Status', kind: 'text' },
      { key: 'starts_at', label: 'Starts at', kind: 'date' },
      { key: 'ends_at', label: 'Ends at', kind: 'date' },
      { key: 'site_name', label: 'Location', kind: 'text' },
      { key: 'instructor_name', label: 'Instructor', kind: 'text' },
      { key: 'capacity', label: 'Capacity', kind: 'number' },
      { key: 'notes', label: 'Notes', kind: 'text' },
      { key: 'attendee_count', label: 'Attendee count', kind: 'number' },
      { key: 'attended_count', label: 'Attended count', kind: 'number' },
      { key: 'absent_count', label: 'Absent count', kind: 'number' },
      { key: 'attendee_emails', label: 'Attendee emails', kind: 'text' },
      // raw enum + FK ids for conditions / recipient `field` targets.
      { key: 'status', label: 'Status (raw)', kind: 'enum' },
      { key: 'course_id', label: 'Course (id)', kind: 'text' },
      { key: 'site_org_unit_id', label: 'Location (id)', kind: 'org_unit' },
      { key: 'instructor_tenant_user_id', label: 'Instructor (user id)', kind: 'person' },
    ],
    collections: [
      {
        key: 'attendees',
        label: 'Attendees',
        fields: [
          { key: 'name', label: 'Name', kind: 'text' },
          { key: 'email', label: 'Email', kind: 'text' },
          { key: 'status', label: 'Status', kind: 'text' },
        ],
      },
    ],
  },
  // The 'equipment' subject is WORK ORDERS specifically (its adapter loads an
  // equipment_work_orders row). Assets themselves are the 'equipment-assets'
  // subject below; the vehicle log is 'vehicle-log'.
  equipment: {
    subjectType: 'module',
    subjectKey: 'equipment',
    label: 'Equipment work orders',
    triggers: ['on_create', 'status_change', 'manual'],
    actions: [
      'send_email',
      'notify_role',
      'webhook',
      'change_status',
      'duplicate_record',
      'export_pdf',
    ],
    statusValues: ['open', 'assigned', 'in_progress', 'awaiting_parts', 'closed', 'cancelled'],
    fields: [
      { key: 'reference', label: 'Reference', kind: 'text' },
      { key: 'summary', label: 'Summary', kind: 'text' },
      { key: 'description', label: 'Description', kind: 'text' },
      { key: 'action_taken', label: 'Action taken', kind: 'text' },
      { key: 'status_label', label: 'Status', kind: 'text' },
      { key: 'priority_label', label: 'Priority', kind: 'text' },
      { key: 'equipment_name', label: 'Equipment', kind: 'text' },
      { key: 'site_name', label: 'Site name', kind: 'text' },
      { key: 'assigned_to_name', label: 'Assigned to', kind: 'text' },
      { key: 'reported_by_name', label: 'Reported by', kind: 'text' },
      { key: 'cost', label: 'Cost', kind: 'text' },
      { key: 'opened_at', label: 'Opened at', kind: 'date' },
      { key: 'closed_at', label: 'Closed at', kind: 'date' },
      { key: 'status', label: 'Status (raw)', kind: 'enum' },
      { key: 'assigned_to_tenant_user_id', label: 'Assigned to (user id)', kind: 'person' },
    ],
  },
  // The equipment REGISTER: fires when an asset is registered (draft committed)
  // or its lifecycle status changes (in service → in repair → retired …).
  'equipment-assets': {
    subjectType: 'module',
    subjectKey: 'equipment-assets',
    label: 'Equipment assets',
    triggers: ['on_create', 'status_change', 'manual'],
    actions: ['send_email', 'notify_role', 'webhook', 'export_pdf'],
    statusValues: ['in_service', 'out_of_service', 'in_repair', 'lost', 'retired'],
    fields: [
      { key: 'reference', label: 'Reference', kind: 'text' },
      { key: 'asset_tag', label: 'Asset tag', kind: 'text' },
      { key: 'name', label: 'Name', kind: 'text' },
      { key: 'description', label: 'Description', kind: 'text' },
      { key: 'serial_number', label: 'Serial number', kind: 'text' },
      { key: 'manufacturer', label: 'Manufacturer', kind: 'text' },
      { key: 'model', label: 'Model', kind: 'text' },
      { key: 'vin', label: 'VIN', kind: 'text' },
      { key: 'license_plate', label: 'License plate', kind: 'text' },
      { key: 'category_name', label: 'Category', kind: 'text' },
      { key: 'type_name', label: 'Type', kind: 'text' },
      { key: 'ownership', label: 'Ownership', kind: 'text' },
      { key: 'status_label', label: 'Status', kind: 'text' },
      { key: 'status', label: 'Status (raw)', kind: 'enum' },
      { key: 'site_name', label: 'Location', kind: 'text' },
      { key: 'holder_name', label: 'Current holder', kind: 'text' },
      // FK ids for conditions / recipient `field` targets.
      { key: 'holder_person_id', label: 'Holder (person id)', kind: 'person' },
      { key: 'site_org_unit_id', label: 'Location (id)', kind: 'org_unit' },
    ],
  },
  // Equipment INSPECTIONS — one equipment_inspection_records row. Fires when
  // the inspection is submitted (result written, work orders spawned); the
  // legacy "Equipment Inspection — [name] (date)" email is an on_submit flow.
  'equipment-inspections': {
    subjectType: 'module',
    subjectKey: 'equipment-inspections',
    label: 'Equipment inspections',
    triggers: ['on_submit', 'manual'],
    actions: ['send_email', 'notify_role', 'create_capa', 'webhook', 'export_pdf'],
    fields: [
      { key: 'reference', label: 'Reference', kind: 'text' },
      { key: 'status_label', label: 'Status', kind: 'text' },
      { key: 'result_label', label: 'Result', kind: 'text' },
      { key: 'type_name', label: 'Inspection type', kind: 'text' },
      { key: 'equipment_name', label: 'Equipment', kind: 'text' },
      { key: 'asset_tag', label: 'Asset tag', kind: 'text' },
      { key: 'serial', label: 'Serial number', kind: 'text' },
      { key: 'interval_label', label: 'Interval', kind: 'text' },
      { key: 'occurred_at', label: 'Occurred at', kind: 'date' },
      { key: 'next_due_on', label: 'Next due on', kind: 'date' },
      { key: 'hours', label: 'Hours reading', kind: 'text' },
      { key: 'is_rental', label: 'Rental', kind: 'text' },
      { key: 'site_name', label: 'Site name', kind: 'text' },
      { key: 'inspector_name', label: 'Inspector', kind: 'text' },
      { key: 'notes', label: 'Notes', kind: 'text' },
      // raw enums + FK ids for conditions / recipient `field` targets.
      { key: 'status', label: 'Status (raw)', kind: 'enum' },
      { key: 'result', label: 'Result (raw)', kind: 'enum' },
      { key: 'equipment_item_id', label: 'Equipment (id)', kind: 'text' },
      { key: 'inspection_type_id', label: 'Inspection type (id)', kind: 'text' },
      { key: 'site_org_unit_id', label: 'Site (id)', kind: 'org_unit' },
      { key: 'inspector_tenant_user_id', label: 'Inspector (user id)', kind: 'person' },
      { key: 'inspector_person_id', label: 'Inspector (person id)', kind: 'person' },
    ],
    collections: [
      {
        key: 'criteria',
        label: 'Inspection items',
        fields: [
          { key: 'group', label: 'Group', kind: 'text' },
          { key: 'question', label: 'Item', kind: 'text' },
          { key: 'answer', label: 'Answer', kind: 'text' },
          { key: 'severity', label: 'Severity', kind: 'text' },
          { key: 'comment', label: 'Comment', kind: 'text' },
          { key: 'action_taken', label: 'Action taken', kind: 'text' },
        ],
      },
      {
        key: 'photos',
        label: 'Photos',
        fields: [
          { key: 'url', label: 'Image URL', kind: 'text' },
          { key: 'caption', label: 'Caption', kind: 'text' },
        ],
      },
    ],
  },
  // PPE INSPECTIONS — one ppe_inspections row (pre-use or annual check on a
  // PPE item). The legacy "PPE Inspection (date)" email is an on_submit flow.
  // Per-criterion answers are not persisted by the PPE model, so this subject
  // carries the derived result + notes, not a criteria collection.
  ppe: {
    subjectType: 'module',
    subjectKey: 'ppe',
    label: 'PPE inspections',
    triggers: ['on_submit', 'manual'],
    actions: ['send_email', 'notify_role', 'create_capa', 'webhook', 'export_pdf'],
    fields: [
      { key: 'reference', label: 'Reference', kind: 'text' },
      { key: 'kind_label', label: 'Inspection kind', kind: 'text' },
      { key: 'result_label', label: 'Result', kind: 'text' },
      { key: 'inspected_on', label: 'Inspected on', kind: 'date' },
      { key: 'next_due_on', label: 'Next due on', kind: 'date' },
      { key: 'notes', label: 'Notes', kind: 'text' },
      { key: 'type_name', label: 'PPE type', kind: 'text' },
      { key: 'type_category', label: 'PPE category', kind: 'text' },
      { key: 'item_serial', label: 'Serial number', kind: 'text' },
      { key: 'item_size', label: 'Size', kind: 'text' },
      { key: 'holder_name', label: 'Issued to', kind: 'text' },
      { key: 'inspector_name', label: 'Inspected by', kind: 'text' },
      // raw enums + FK ids for conditions / recipient `field` targets.
      { key: 'kind', label: 'Kind (raw)', kind: 'enum' },
      { key: 'result', label: 'Result (raw)', kind: 'enum' },
      { key: 'item_id', label: 'PPE item (id)', kind: 'text' },
      { key: 'type_id', label: 'PPE type (id)', kind: 'text' },
      { key: 'holder_person_id', label: 'Holder (person id)', kind: 'person' },
      { key: 'inspected_by_tenant_user_id', label: 'Inspector (user id)', kind: 'person' },
    ],
  },
  // The subject row is one truck_log_entries record, but its value map carries
  // the whole driver+vehicle month (totals + the `entries` collection) — so a
  // PDF/email template renders the legacy monthly sheet. `on_submit` fires on
  // every manual save from the workspace grid.
  'vehicle-log': {
    subjectType: 'module',
    subjectKey: 'vehicle-log',
    label: 'Vehicle log',
    triggers: ['on_submit', 'manual'],
    actions: ['send_email', 'notify_role', 'webhook', 'export_pdf'],
    fields: [
      { key: 'reference', label: 'Reference', kind: 'text' },
      { key: 'entry_date', label: 'Entry date', kind: 'date' },
      { key: 'entry_mode', label: 'Entry mode', kind: 'enum' },
      { key: 'driver_name', label: 'Driver', kind: 'text' },
      { key: 'driver_employee_no', label: 'Driver employee #', kind: 'text' },
      { key: 'vehicle_name', label: 'Vehicle', kind: 'text' },
      { key: 'site_name', label: 'Site name', kind: 'text' },
      { key: 'other_destination', label: 'Other destination', kind: 'text' },
      { key: 'start_odometer', label: 'Start odometer', kind: 'number' },
      { key: 'end_odometer', label: 'End odometer', kind: 'number' },
      { key: 'business_km', label: 'Business km', kind: 'number' },
      { key: 'personal_km', label: 'Personal km', kind: 'number' },
      { key: 'total_km', label: 'Total km', kind: 'number' },
      { key: 'hours_on_site', label: 'Hours on site', kind: 'text' },
      { key: 'crew_count', label: 'Crew count', kind: 'number' },
      { key: 'notes', label: 'Notes', kind: 'text' },
      { key: 'month_key', label: 'Month (YYYY-MM)', kind: 'text' },
      { key: 'month_label', label: 'Month', kind: 'text' },
      { key: 'month_days_logged', label: 'Month days logged', kind: 'number' },
      { key: 'month_business_km', label: 'Month business km', kind: 'number' },
      { key: 'month_personal_km', label: 'Month personal km', kind: 'number' },
      { key: 'month_total_km', label: 'Month total km', kind: 'number' },
      { key: 'month_hours_on_site', label: 'Month hours on site', kind: 'text' },
      // FK ids for conditions / recipient `field` targets.
      { key: 'driver_person_id', label: 'Driver (person id)', kind: 'person' },
      { key: 'equipment_item_id', label: 'Vehicle (equipment id)', kind: 'text' },
      { key: 'site_org_unit_id', label: 'Site (id)', kind: 'org_unit' },
    ],
    collections: [
      {
        key: 'entries',
        label: 'Month log entries',
        fields: [
          { key: 'date', label: 'Date', kind: 'date' },
          { key: 'day', label: 'Day', kind: 'number' },
          { key: 'weekday', label: 'Weekday', kind: 'text' },
          { key: 'site_name', label: 'Customer / site', kind: 'text' },
          { key: 'other_destination', label: 'Other destination', kind: 'text' },
          { key: 'start_odometer', label: 'Start odometer', kind: 'number' },
          { key: 'end_odometer', label: 'End odometer', kind: 'number' },
          { key: 'business_km', label: 'Business km', kind: 'number' },
          { key: 'personal_km', label: 'Personal km', kind: 'number' },
          { key: 'total_km', label: 'Total km', kind: 'number' },
          { key: 'hours_on_site', label: 'Hours on site', kind: 'text' },
          { key: 'crew_count', label: 'Crew count', kind: 'number' },
          { key: 'notes', label: 'Notes', kind: 'text' },
        ],
      },
    ],
  },
  documents: {
    subjectType: 'module',
    subjectKey: 'documents',
    label: 'Documents',
    triggers: ['on_create', 'manual'],
    actions: ['send_email', 'notify_role', 'webhook', 'export_pdf', 'duplicate_record'],
    fields: [
      { key: 'title', label: 'Title', kind: 'text' },
      { key: 'period_start', label: 'Period start', kind: 'date' },
      { key: 'period_end', label: 'Period end', kind: 'date' },
      { key: 'next_review_on', label: 'Next review on', kind: 'date' },
      { key: 'chair_name', label: 'Chaired by', kind: 'text' },
      { key: 'owner_name', label: 'Created by', kind: 'text' },
      { key: 'discussion_notes', label: 'Discussion notes', kind: 'text' },
      { key: 'decisions', label: 'Decisions', kind: 'text' },
    ],
    collections: [
      {
        key: 'attendees',
        label: 'Attendees',
        fields: [
          { key: 'name', label: 'Name', kind: 'text' },
          { key: 'email', label: 'Email', kind: 'text' },
        ],
      },
      {
        key: 'documents_reviewed',
        label: 'Documents reviewed',
        fields: [
          { key: 'title', label: 'Document', kind: 'text' },
          { key: 'status', label: 'Status', kind: 'text' },
        ],
      },
      {
        key: 'action_items',
        label: 'Action items',
        fields: [
          { key: 'reference', label: 'Reference', kind: 'text' },
          { key: 'title', label: 'Title', kind: 'text' },
          { key: 'status', label: 'Status', kind: 'text' },
          { key: 'due_on', label: 'Due on', kind: 'text' },
        ],
      },
    ],
  },
}

export function moduleFlowProfile(moduleKey: string): FlowSubjectProfile | null {
  return MODULE_FLOW_PROFILES[moduleKey] ?? null
}
