import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { resolve, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'
import { systemMessageKey } from '@beaconhs/i18n/key'

const repository = resolve(fileURLToPath(new URL('../../..', import.meta.url)))
const target = resolve(repository, 'apps/web/src/i18n/client-message-keys.ts')
const catalog = JSON.parse(
  readFileSync(resolve(repository, 'packages/i18n/src/messages/en.json'), 'utf8'),
).Generated as Record<string, string>

/** Keep runtime copy from public app/packages; long guide bodies are translated on the server. */
export function collectClientMessageKeys(): string[] {
  const keys = new Set<string>()
  function scan(directory: string) {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const file = resolve(directory, entry.name)
      if (entry.isDirectory()) {
        if (!['node_modules', 'dist', '.next', '.turbo', 'messages', 'etl'].includes(entry.name))
          scan(file)
        continue
      }
      if (
        !/\.(?:[cm]?tsx?|json)$/.test(entry.name) ||
        /\.(?:test|spec)\./.test(entry.name) ||
        file === target
      )
        continue
      const source = ts.createSourceFile(
        file,
        readFileSync(file, 'utf8'),
        ts.ScriptTarget.Latest,
        true,
        entry.name.endsWith('.json') ? ts.ScriptKind.JSON : undefined,
      )
      function visit(node: ts.Node) {
        if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
          const guideBody =
            relative(repository, file).includes('lib/manual/content/') &&
            ts.isPropertyAssignment(node.parent) &&
            node.parent.name.getText(source) === 'body'
          if (!guideBody) {
            const key = /^m_[a-f0-9]{14}$/.test(node.text) ? node.text : systemMessageKey(node.text)
            if (catalog[key] !== undefined) keys.add(key)
          }
        }
        ts.forEachChild(node, visit)
      }
      visit(source)
    }
  }
  scan(resolve(repository, 'apps/web/src'))
  for (const entry of readdirSync(resolve(repository, 'packages'), { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === 'etl') continue
    const source = resolve(repository, 'packages', entry.name, 'src')
    try {
      scan(source)
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
    }
  }
  return [...keys].sort()
}

export function renderClientMessageKeys(keys: readonly string[]): string {
  return `// Generated by pnpm --filter @beaconhs/web i18n:client-messages.\n// Canonical translations stay in @beaconhs/i18n; this lists active UI lookup keys only.\nexport const CLIENT_MESSAGE_KEYS: readonly string[] = [\n${keys.map((key) => `  '${key}',`).join('\n')}\n]\n`
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const keys = collectClientMessageKeys()
  writeFileSync(target, renderClientMessageKeys(keys))
  console.log(
    `Selected ${keys.length} UI messages (${Buffer.byteLength(JSON.stringify(Object.fromEntries(keys.map((key) => [key, catalog[key]]))))} bytes). Guide bodies stay server-side.`,
  )
}
