DO $$
DECLARE t record;
BEGIN
  FOR t IN SELECT id FROM tenants LOOP
    PERFORM set_config('app.tenant_id', t.id::text, true);
    UPDATE report_definitions SET query = '{"entity":"skill_assignments","mode":"rows","columns":["employee_no","last_name","first_name","authority","certification_code","certification_name","expires_on","status"],"filters":{"combinator":"and","rules":[{"field":"status","op":"in","value":["expired","expiring"]}]},"groupBy":"certification_name","sort":null,"sorts":[{"column":"expires_on","direction":"asc"}],"limit":5000}'::jsonb, layout = '{"paperSize":"letter","orientation":"portrait","marginMm":15,"showSummary":true,"density":"standard"}'::jsonb, updated_at = now() WHERE tenant_id = t.id AND seed_key = 'skills_expired_upcoming';
    UPDATE report_definitions SET query = '{"entity":"skill_coverage","mode":"rows","columns":["employee_no","person_name","department_name","skill_name","authority","coverage_status","expires_on"],"filters":{"combinator":"and","rules":[{"field":"person_status","op":"eq","value":"active"},{"field":"is_required","op":"is_true"},{"field":"coverage_status","op":"in","value":["missing","expired","expiring"]}]},"groupBy":"skill_name","sort":null,"sorts":[{"column":"person_name","direction":"asc"}],"limit":5000}'::jsonb, layout = '{"paperSize":"letter","orientation":"portrait","marginMm":15,"showSummary":true,"density":"standard"}'::jsonb, updated_at = now() WHERE tenant_id = t.id AND seed_key = 'skills_missing';
    UPDATE report_definitions SET query = '{"entity":"skill_assignments","mode":"rows","columns":["person_name","cwb_type","cwb_process","cwb_position","cwb_level","expires_on","authority_code","shop_field_layoff"],"filters":{"combinator":"and","rules":[{"field":"authority_code","op":"eq","value":"CWB"},{"field":"outcome","op":"eq","value":"complete"}]},"groupBy":"cwb_standard","sort":null,"sorts":[{"column":"last_name","direction":"asc"},{"column":"first_name","direction":"asc"}],"limit":5000}'::jsonb, layout = '{"paperSize":"letter","orientation":"portrait","marginMm":15,"showSummary":true,"density":"compact"}'::jsonb, updated_at = now() WHERE tenant_id = t.id AND seed_key = 'skills_cwb';
    UPDATE report_schedules SET active = false WHERE tenant_id = t.id AND definition_id IN (SELECT id FROM report_definitions WHERE tenant_id = t.id AND seed_key = 'skills_matrix');
    UPDATE report_definitions SET state = 'archived' WHERE tenant_id = t.id AND seed_key = 'skills_matrix';
    DELETE FROM report_definitions d WHERE d.tenant_id = t.id AND d.seed_key = 'skills_matrix' AND NOT EXISTS (SELECT 1 FROM report_schedules s WHERE s.definition_id = d.id);
    INSERT INTO insight_cards (tenant_id, name, description, query, viz_type, viz_settings, status, published_at)
      SELECT t.id, 'Training — Skills Matrix', 'Active employees by skill, with current qualification coverage.', '{"version":"bhql/1","display":"pivot","pivot":{"rows":[{"breakout":"person_name"}],"columns":[{"breakout":"skill_name"}],"values":[{"measure":"coverage_status"}]},"stages":[{"source":"skill_coverage","filter":{"combinator":"and","rules":[{"field":"person_status","op":"eq","value":"active"}]},"breakouts":[{"alias":"person_name","field":"person_name"},{"alias":"skill_name","field":"skill_name"}],"aggregations":[{"kind":"expr","alias":"coverage_status","expr":{"ex":"agg","fn":"min","arg":{"ex":"case","branches":[{"when":{"ex":"logic","op":"and","args":[{"ex":"compare","op":"=","left":{"ex":"field","field":"coverage_status"},"right":{"ex":"lit","value":"missing"}},{"ex":"compare","op":"=","left":{"ex":"field","field":"is_required"},"right":{"ex":"lit","value":false}}]},"then":{"ex":"lit","value":null}}],"else":{"ex":"field","field":"coverage_status"}}}}]}]}'::jsonb, 'pivot', '{}'::jsonb, 'published', now()
      WHERE NOT EXISTS (SELECT 1 FROM insight_cards WHERE tenant_id = t.id AND name = 'Training — Skills Matrix' AND created_by IS NULL AND deleted_at IS NULL);
  END LOOP;
END $$;
