// GET /training/records/:id/certificate?format=cert|wallet
//
// Resolves the training_certificate row for the given record (or creates one
// implicitly: the worker job creates certificates on demand if the cert row
// exists). Returns:
//   - 307 redirect to a signed GET URL on the latest PDF (cert by default)
//   - 202 if no PDF exists yet and a render job has been enqueued
//
// `format=wallet` redirects to the wallet card variant.
// `format=cert` (default) redirects to the full-size certificate.

import { NextResponse, type NextRequest } from 'next/server'
import { and, desc, eq, like } from 'drizzle-orm'
import { attachments, trainingCertificates } from '@beaconhs/db/schema'
import { presignGet } from '@beaconhs/storage'
import { requireRequestContext } from '@/lib/auth'
import { requestCertificatePdf } from '@/lib/pdf-actions'

export const dynamic = 'force-dynamic'

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
): Promise<Response> {
  const { id: recordId } = await params
  const format = (req.nextUrl.searchParams.get('format') ?? 'cert').toLowerCase()
  const wantWallet = format === 'wallet'

  const ctx = await requireRequestContext()
  if (!ctx.tenantId) {
    return NextResponse.json({ error: 'No active tenant' }, { status: 400 })
  }

  const result = await ctx.db(async (tx) => {
    const [cert] = await tx
      .select()
      .from(trainingCertificates)
      .where(eq(trainingCertificates.recordId, recordId))
      .orderBy(desc(trainingCertificates.createdAt))
      .limit(1)
    if (!cert) return { cert: null, latestAttachment: null }

    // For the full certificate we trust trainingCertificates.pdfAttachmentId.
    // For the wallet card we look up the most recent wallet attachment
    // generated by the worker (we don't store an FK for it because there's
    // only one wallet slot to hold and the cert FK already exists).
    if (wantWallet) {
      const [wallet] = await tx
        .select({ att: attachments })
        .from(attachments)
        .where(
          and(
            eq(attachments.tenantId, ctx.tenantId!),
            eq(attachments.contentType, 'application/pdf'),
            like(attachments.r2Key, `pdfs/certificates/${cert.id}-wallet-%`),
          ),
        )
        .orderBy(desc(attachments.createdAt))
        .limit(1)
      return { cert, latestAttachment: wallet?.att ?? null }
    }

    if (cert.pdfAttachmentId) {
      const [att] = await tx
        .select()
        .from(attachments)
        .where(eq(attachments.id, cert.pdfAttachmentId))
        .limit(1)
      return { cert, latestAttachment: att ?? null }
    }
    return { cert, latestAttachment: null }
  })

  if (!result.cert) {
    return NextResponse.json(
      { error: 'No certificate has been issued for this record yet.' },
      { status: 404 },
    )
  }

  if (result.latestAttachment) {
    const url = await presignGet({ key: result.latestAttachment.r2Key, expiresInSeconds: 300 })
    return NextResponse.redirect(url, { status: 307 })
  }

  // Kick off render — produces both wallet + cert.
  const enq = await requestCertificatePdf(result.cert.id)
  if (!enq.ok) {
    return NextResponse.json({ error: enq.error }, { status: 400 })
  }
  return new NextResponse('Certificate is being generated. Refresh in a few seconds.', {
    status: 202,
    headers: {
      'Retry-After': '5',
      'Content-Type': 'text/plain; charset=utf-8',
    },
  })
}
